### ISSUE TITLE
Casting issue

### ISSUE THREAD

**Issue by GjoAbrahamN** [tjoshi03/otpreaderview#1]
Problem arising in _Mainactivity_  ,Here otp declare as a Textview but in the XML view it is '_com.example.apple.demo.View.OtpView_' thats why rising an error '_java.lang.classcastexception_' please solve the issue.

**Comment by tjoshi03** [comment]
sorry for inconvenient please Change Textview to OtpView and otp.settext to otp.setotp in main activity of example. other wise download again the whole project i make the changes

**Comment by GjoAbrahamN** [comment]
Fast move..good

**Comment by tjoshi03** [comment]
thanks for the feedback issue is solve you can do changes according to i say or you can download full code again

**Comment by GjoAbrahamN** [comment]
i changed the code accordingly , thanks

**Comment by GjoAbrahamN** [comment]
Hi, bro i have changed the code accordingly , and i can toast the incoming message , but can't be set it into the OtpView. do you have any idea about the problem?

**Comment by GjoAbrahamN** [comment]
You have to change the mOtpOneField.setText(text.charAt(0)) in the otpview.java class As 
mOtpOneField.setText(String.valueOf(text.charAt(0))), also the next 3 lines of code.

**Comment by tjoshi03** [comment]
String regex = "[^\\d]+";
       final String[] str = message.split(regex);
otp.setOTP(str[1]);
also add this code in otpReceive method 

or you can download project again
